### ISSUE TITLE
Subdivision - trim_coeff

### ISSUE THREAD

**Issue by mtmoncur** [tylerjarvis/RootFinding#93]
Right now, trim_coeff starts by setting small elements of coeff[0] to zero. This seems odd that we only do this for the first dimension and not coeff[:,0] or coeff[:,:,0]. Or why not do this for all of coeff? Is this intended?

**Comment by tylerjarvis** [comment]
This seems strange to me, too. 
It is possible that certain coeffs might need to stay nonzero, depending on which coefficient we multiply by or divide by later, but surely all the other coefficients should be set to zero if they are very small.

@erikhparkinson  might be able to provide some insight.

**Comment by erikhparkinson** [comment]
Yeah, I was constantly adjusting with and playing around with what was being trimmed or not, so if it looks like it could be improved feel free to change that. My reasoning when writing it as I did was 

1. We want to change the coefficients as little as possible so that we have as accurate of an approximation as possible 

2. If we are dividing by x, then we need all of the terms without an x in them to be pivot columns in the Macaulay Matrix. So for the sake of stability we want these all to be decently big, so we get rid of anything here that is smaller than some determined size (One of the tolerance parameters given.) I believe this is the trim coeff[0] Tyler mentions.

3. We already loose some precision for sure by getting rid of these terms, so we might as well get rid of some of the even smaller ones of high degree. If we can make the degree smaller it will decrease the size of the Macaulay matrix we create and thus save a lot of time. So it checks how many diagonals it can trim off and not loose any more precision than we already lost (how far it trims the diagonals is the other tolerance parameter).
